### PR TITLE
Add Autoarchive > AutoarchiveReloaded mapping

### PR DESCRIPTION
**Pull request by Brummolix**

### CODE REVIEW

**Comment by jobisoft** [comment]
Are you planing to remove the Experiment (soon)? 
Can you say something about the data loss cases? Are they related to the messages API? Something I can improve?

**Comment by Brummolix** [comment]
The experiment is now only needed to convert configuration settings of older installations (before new extension system). I had to check how many users have upgraded already and depending on that number its definitely a good idea to remove the experiment at all.

The data losses are a pitty. Unfortunately I never managed to reproduce them. Neither could users reproduce it a second time (but after already loosing data, the willingness to try a lot of things is low...)
As the addon is "only" calling the integrated archive function of thunderbird (for many messages at once and in many sub folders at once) and never deleting any messages it seem to be a bug inside thunderbird. I also assume that something similar could happen if you select a lot of message in the thunderbird UI and then choose to archive them all via normal thunderbird archive function.

Here are some issues from github
https://github.com/Brummolix/AutoarchiveReloaded/issues/61
https://github.com/Brummolix/AutoarchiveReloaded/issues/14
https://github.com/Brummolix/AutoarchiveReloaded/issues/8

**Comment by jobisoft** [comment]
Would it be ok for you, if I postpone this PR until the Experiment has been removed? I will have a closer look at those issues as well.
Just ping back here, once you have released a new version.

**Comment by Brummolix** [comment]
OK

**Comment by Brummolix** [comment]
Just released a new version without experiment

**Pull request merged**
